spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: bokadev@sandbox0f3ef819477849e7bd94a1f98f768c67.mailgun.org\

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true


chirp:
  email:
    url: "httos://chirp.bokadev.me"
  rate-limit:
    ip:
      apply-limit: true
  websocket:
    allowed-origin: "https://chirp.bokadev.me"